modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "zombietactics2"
version = "$version"
displayName = "Zombie Tactics 2"
authors = "picopress"
description = "Improves zombie mechanism"
logoFile = "assets/zombietactics2/img.png"

[[dependencies.zombietactics2]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombietactics2]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.zombietactics2]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "zombietactics2.forge-mixins.json"

[[mixins]]
config = "zombietactics2.mixins.json"
