# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.1.2+1.21.5
maven_group = picopress
archives_name = zombietactics2
enabled_platforms = fabric,neoforge
change_log = ""

# Minecraft properties
minecraft_version = 1.21.5

# NeoForge
neoforge_version = 21.5.73-beta
moddev_version = 2.0.89
parchment_version = 1.21.5:2025.04.19

# Fabric
fabric_loom_version = 1.10-SNAPSHOT
fabric_loader_version = 0.16.14
fabric_api_version = 0.125.0+1.21.5
yarn_mappings = 1.21.5+build.1

# Dependencies
architectury_api_version = 16.1.4
midnightlib_version = 1.7.3+1.21.4-fabric
modmenu_version = 14.0.0-rc.2
